In [122]:
list1 = list([['허준호', '남자', 30, 183],
 ['이가원', '여자', 24, 162],
 ['배규민', '남자', 23, 179],
 ['고고림', '남자', 21, 182],
 ['이새봄', '여자', 28, 160],
 ['이보람', '여자', 26, 163],
 ['이루리', '여자', 24, 157],
 ['오다현', '여자', 24, 172]])

In [124]:
list1

[['허준호', '남자', 30, 183],
 ['이가원', '여자', 24, 162],
 ['배규민', '남자', 23, 179],
 ['고고림', '남자', 21, 182],
 ['이새봄', '여자', 28, 160],
 ['이보람', '여자', 26, 163],
 ['이루리', '여자', 24, 157],
 ['오다현', '여자', 24, 172]]

문자열로 처리하고 있다 ==> numpy의 ndarray로 처리 가능하다

In [127]:
type(list1)

list

자료형에 대해 알아야하는 것 ==> 각 자료마다 사용가능한 메소드가 다르기 때문임

In [130]:
list1[1]

['이가원', '여자', 24, 162]

여자라는 성별을 알고싶다. list1[1,1]? 안된다 python의 list객체는 이러한 접근이 허용되지 않는다 ==> list[1][1]

In [133]:
list1[1][1]

'여자'

클래스가 다르다는 것은 객체에 대한 정의가 다르다는 뜻이기에... 클래스에 대한 정의가 올바른지 확인하는 것이 디버깅의 시작이다.


기본은 입력과 출력에 대한 것에 정의가 잘 되어야 한다.



이러한 언어들에 대한 기본에 출실하는 것이 실전에 대한 준비이며, 예의이다.

list1을 numpy형태로 만들고 싶다면 아래처럼 한다.

In [137]:
import numpy as np
numlist = np.array(list1)

In [139]:
numlist[1,1]

'여자'

In [141]:
import pandas as pd
col_names = ['이름','성별','나이','키']
df = pd.DataFrame(data =list1, columns=col_names)
df

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

pandas는 인간친화적인(접근성이 높은) 패키지이다

pandas의 descirbe()함수는 데이터에 대해 기초통계학을 사용한 각각의 정보를 보여준다.

In [28]:
df.describe()

              나이           키
count   8.000000    8.000000
mean   25.000000  169.750000
std     2.878492   10.552589
min    21.000000  157.000000
25%    23.750000  161.500000
50%    24.000000  167.500000
75%    26.500000  179.750000
max    30.000000  183.000000

혈액형을 조사하면 a형은 몇명, b형은 몇명 등 양이 아닌 질적 통계가 필요함 ==> 평균분산은 양적 데이터를 다룰때 사용한다.

따라서 질적 데이터를 볼때에는 또 다른 것을 사용해야하고, 이는 프로그래밍도 마찬가지이다.

통계학, 코딩도 데이터 형식 -질적데이터, 양적데이터, 문자열, 정수형 등- 에 따른 문제해결방식(메소드)가 다르다.

분석을 할 떄에는 coloum단위의 데이터 조회를 하게 된다.

In [34]:
def test(name, gender, age, height):
    print('이름: '+ name, end=", ")
    print('성별: ' + gender, end=", ")
    print('나이: ',age, end=", ")
    print('키: ',height)
    

test('홍길동', '남자', 20, 180)

이름: 홍길동, 성별: 남자, 나이:  20, 키:  180

In [36]:
test('홍길동','남자',height=180,age=20)

이름: 홍길동, 성별: 남자, 나이:  20, 키:  180

개념만 이해하면, 객체지향으로의 입문은 쉽다 ==> 철학적 의미가 중요하기 때문이다

또한 함수 내에서 디폴트 값을 지정할 수 있다 ==> 또한 디폴트 값을 지정할 때엔 항상 뒤에서 부터 지정해줘야한다.

In [40]:
def test(name, gender, height, age=20):
    print('이름: '+ name, end=", ")
    print('성별: ' + gender, end=", ")
    print('나이: ',age, end=", ")
    print('키: ',height)

In [42]:
test('홍길동', '남성', 180)

이름: 홍길동, 성별: 남성, 나이:  20, 키:  180

함수를 사용하고 디폴트값을 변경해줄 때에도 뒤에서 부터 지정해줘야한다.

In [45]:
test('홍길동', '남성', 180, age=30)

이름: 홍길동, 성별: 남성, 나이:  30, 키:  180

이제부터 본격적으로 데이터를 활용하는 방식에 대해 설명할 것이다.

In [48]:
df.columns

Index(['이름', '성별', '나이', '키'], dtype='object')

In [50]:
df[['성별', '이름']]

   성별   이름
0  남자  허준호
1  여자  이가원
2  남자  배규민
3  남자  고고림
4  여자  이새봄
5  여자  이보람
6  여자  이루리
7  여자  오다현

In [52]:
type(df['성별'])

pandas.core.series.Series

In [54]:
df.loc[[4]]

    이름  성별  나이    키
4  이새봄  여자  28  160

In [56]:
df.loc[4]

이름    이새봄
성별     여자
나이     28
키     160
Name: 4, dtype: object

In [58]:
df.iloc[1,:]

이름    이가원
성별     여자
나이     24
키     162
Name: 1, dtype: object

iloc같은 경우 index를 포함한 것을 제공해줘야한다. 따라서 iloc를 사용해서 index기반 슬라이징, 인덱싱을 하자

키 값을 180보다 큰것을 사용하고 싶을 때

In [62]:
df['키']>180

0     True
1    False
2    False
3     True
4    False
5    False
6    False
7    False
Name: 키, dtype: bool

In [64]:
df['성별'] == '여자'

0    False
1     True
2    False
3    False
4     True
5     True
6     True
7     True
Name: 성별, dtype: bool

이제 조건을 만족하는 데이터를 출력해보자

파이썬의 가장 큰 특징을 활용

조건식을 넣어준다.

In [68]:
df[df['성별']=='남자']

    이름  성별  나이    키
0  허준호  남자  30  183
2  배규민  남자  23  179
3  고고림  남자  21  182

In [70]:
df[df['이름'].str.contains('봄')]

    이름  성별  나이    키
4  이새봄  여자  28  160

In [72]:
df.iloc[1:5,0:2]

    이름  성별
1  이가원  여자
2  배규민  남자
3  고고림  남자
4  이새봄  여자

df.loc[1:5,0:2] ==> 이 코드는 돌아가지 않을 것이다.

loc같은경우 인덱스, 레이블의 값을 받기 때문임

In [75]:
df.loc[1:5, ['이름','성별']]

    이름  성별
1  이가원  여자
2  배규민  남자
3  고고림  남자
4  이새봄  여자
5  이보람  여자

loc같은 경우 인덱스와 colunmsdml 형태를 입력해줘야 한다.

In [78]:
df.loc[1:3,'키'] = ['모름'] * 3
df

C:\Users\plane\AppData\Local\Temp\ipykernel_10040\1321750272.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['모름', '모름', '모름']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[1:3,'키'] = ['모름'] * 3

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24   모름
2  배규민  남자  23   모름
3  고고림  남자  21   모름
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

여기서는 df를 다시 키값을 원데이터로 돌아가겠다.

여기서 df값을 변경하기엔 배울 것이 있기 때문임

In [81]:
df

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24   모름
2  배규민  남자  23   모름
3  고고림  남자  21   모름
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [83]:
df.dtypes

이름    object
성별    object
나이     int64
키     object
dtype: object

In [108]:
df.astype({'나이':'int32'},{'키':'int64'})

    이름  성별  나이    키
0  허준호  남자  30  183
1  이가원  여자  24   모름
2  배규민  남자  23   모름
3  고고림  남자  21   모름
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [145]:
df.dtypes

이름    object
성별    object
나이     int64
키      int64
dtype: object

In [149]:
df[df['키']>180]

    이름  성별  나이    키
0  허준호  남자  30  183
3  고고림  남자  21  182

In [151]:
df[df['성별']=='남자']

    이름  성별  나이    키
0  허준호  남자  30  183
2  배규민  남자  23  179
3  고고림  남자  21  182

In [153]:
df[(df['성별']=='남자') & (df['키']>180)]

    이름  성별  나이    키
0  허준호  남자  30  183
3  고고림  남자  21  182

In [159]:
df['키'].mean()

169.75

In [161]:
df.describe()

              나이           키
count   8.000000    8.000000
mean   25.000000  169.750000
std     2.878492   10.552589
min    21.000000  157.000000
25%    23.750000  161.500000
50%    24.000000  167.500000
75%    26.500000  179.750000
max    30.000000  183.000000