In [276]:
import time
from bs4 import BeautifulSoup
from selenium import webdriver

url = "https://comic.naver.com/index"
driver = webdriver.Edge()
driver.get(url)
time.sleep(3)

soup = BeautifulSoup(driver.page_source, 'html.parser')

title = soup.select("li.AsideList__item--i30ly span.ContentTitle__title--e3qXt")
author = soup.select("li.AsideList__item--i30ly a.ContentAuthor__author--CTAAP")

driver.quit()

for i in range(5): print(f'순위: {i+1}, 제목: {title[i].text}, 작가: {author[i].text}')

순위: 1, 제목: 참교육, 작가: 채용택 / 한가람
순위: 2, 제목: 외모지상주의, 작가: 박태준
순위: 3, 제목: 퀘스트지상주의, 작가: 박만사, 유누니 / 박만사, 태완
순위: 4, 제목: 윈드브레이커, 작가: 조용석
순위: 5, 제목: 화산귀환, 작가: LICO / 비가

In [284]:
import requests
from bs4 import BeautifulSoup
 
url = "https://comic.naver.com/api/realtime/ranking/list?rankTabType=DEFAULT"
response = requests.get(url)
response.text

'{"defaultSortType":"total","totalRankingTitleList":[{"rank":1,"rankUp":1,"titleId":821597,"titleName":"괴력 난신","author":{"writers":[{"id":375577,"name":"매드버드"}],"painters":[{"id":375579,"name":"김태형"}],"originAuthors":[{"id":347598,"name":"한중월야"}]},"displayAuthor":"매드버드 / 김태형 / 한중월야","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/821597/thumbnail/thumbnail_IMAG21_07118c59-2490-4cc9-b144-11c10f138b30.jpg","thumbnailBadgeList":[],"up":true,"rest":false},{"rank":2,"rankDown":1,"titleId":783053,"titleName":"김부장","author":{"writers":[{"id":351540,"name":"박만사"},{"id":364997,"name":"남자의 이야기"}],"painters":[{"id":300655,"name":"정종택","blogUrl":"https://blog.naver.com/jongjt0302"}],"originAuthors":[]},"displayAuthor":"박만사, 남자의 이야기 / 정종택","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/783053/thumbnail/thumbnail_IMAG21_d7732f14-26da-4e35-8762-660cc87b53f1.jpg","thumbnailBadgeList":[],"up":true,"rest":false},{"rank":3,"titleId":730656,"titleName":"사신소년","author":{"writers":[{"id":326532,"name":"류","blogUrl":"https://blog.naver.com/gyeonghun0617"}],"painters":[{"id":326532,"name":"류","blogUrl":"https://blog.naver.com/gyeonghun0617"}],"originAuthors":[]},"displayAuthor":"류","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/730656/thumbnail/thumbnail_IMAG21_fc6d8dbf-eed2-43d0-af45-2edb3cc4244e.jpg","thumbnailBadgeList":[],"up":true,"rest":false},{"rank":4,"titleId":828715,"titleName":"절대회귀","author":{"writers":[{"id":348256,"name":"JP"}],"painters":[{"id":325491,"name":"박진환","blogUrl":"https://blog.naver.com/tdstudio"}],"originAuthors":[{"id":376586,"name":"장영훈"}]},"displayAuthor":"JP / 박진환 / 장영훈","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/828715/thumbnail/thumbnail_IMAG21_8957548a-2eb2-4ddf-a50e-dbc7fddc16a7.jpg","thumbnailBadgeList":[],"up":true,"rest":false},{"rank":5,"titleId":641253,"titleName":"외모지상주의","author":{"writers":[{"id":283063,"name":"박태준","blogUrl":"https://blog.naver.com/thesooha"}],"painters":[{"id":283063,"name":"박태준","blogUrl":"https://blog.naver.com/thesooha"}],"originAuthors":[]},"displayAuthor":"박태준","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/641253/thumbnail/thumbnail_IMAG21_01672165-03c8-44b1-ba0e-ef82c9cfcd10.jpg","thumbnailBadgeList":[],"up":false,"rest":false}],"maleRankingTitleList":[{"rank":1,"titleId":783053,"titleName":"김부장","author":{"writers":[{"id":351540,"name":"박만사"},{"id":364997,"name":"남자의 이야기"}],"painters":[{"id":300655,"name":"정종택","blogUrl":"https://blog.naver.com/jongjt0302"}],"originAuthors":[]},"displayAuthor":"박만사, 남자의 이야기 / 정종택","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/783053/thumbnail/thumbnail_IMAG21_d7732f14-26da-4e35-8762-660cc87b53f1.jpg","thumbnailBadgeList":[],"up":true,"rest":false},{"rank":2,"titleId":821597,"titleName":"괴력 난신","author":{"writers":[{"id":375577,"name":"매드버드"}],"painters":[{"id":375579,"name":"김태형"}],"originAuthors":[{"id":347598,"name":"한중월야"}]},"displayAuthor":"매드버드 / 김태형 / 한중월야","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/821597/thumbnail/thumbnail_IMAG21_07118c59-2490-4cc9-b144-11c10f138b30.jpg","thumbnailBadgeList":[],"up":true,"rest":false},{"rank":3,"titleId":730656,"titleName":"사신소년","author":{"writers":[{"id":326532,"name":"류","blogUrl":"https://blog.naver.com/gyeonghun0617"}],"painters":[{"id":326532,"name":"류","blogUrl":"https://blog.naver.com/gyeonghun0617"}],"originAuthors":[]},"displayAuthor":"류","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/730656/thumbnail/thumbnail_IMAG21_fc6d8dbf-eed2-43d0-af45-2edb3cc4244e.jpg","thumbnailBadgeList":[],"up":true,"rest":false},{"rank":4,"titleId":828715,"titleName":"절대회귀","author":{"writers":[{"id":348256,"name":"JP"}],"painters":[{"id":325491,"name":"박진환","blogUrl":"https://blog.naver.com/tdstudio"}],"originAuthors":[{"id":376586,"name":"장영훈"}]},"displayAuthor":"JP / 박진환 / 장영훈","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/828715/thumbnail/thumbnail_IMAG21_8957548a-2eb2-4ddf-a50e-dbc7fddc16a7.jpg","thumbnailBadgeList":[],"up":true,"rest":false},{"rank":5,"rankUp":1,"titleId":809618,"titleName":"신과함께 돌아온 기사왕님","author":{"writers":[{"id":367063,"name":"지대공마법소년"}],"painters":[{"id":366485,"name":"전천후마검사"}],"originAuthors":[{"id":366484,"name":"사람살려."}]},"displayAuthor":"지대공마법소년 / 전천후마검사 / 사람살려.","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/809618/thumbnail/thumbnail_IMAG21_d3c27ef7-aa89-44d3-8be2-5b102b8aa817.jpg","thumbnailBadgeList":[],"up":true,"rest":false}],"femaleRankingTitleList":[{"rank":1,"titleId":801711,"titleName":"시한부인 줄 알았어요!","author":{"writers":[{"id":359014,"name":"혜용"}],"painters":[{"id":359015,"name":"에시","blogUrl":"https://blog.naver.com/boria_0"}],"originAuthors":[{"id":357680,"name":"최아리"}]},"displayAuthor":"혜용 / 에시 / 최아리","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/801711/thumbnail/thumbnail_IMAG21_2a097d0a-8844-4fb6-93d9-fc04fb3197db.jpg","thumbnailBadgeList":[],"up":true,"rest":false},{"rank":2,"titleId":817247,"titleName":"못 잡아먹어서 안달","author":{"writers":[{"id":371824,"name":"팀 보도뵈"}],"painters":[{"id":347092,"name":"퀀퀀"}],"originAuthors":[{"id":351605,"name":"플아다"}]},"displayAuthor":"팀 보도뵈 / 퀀퀀 / 플아다","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/817247/thumbnail/thumbnail_IMAG21_61bd3fbe-b16f-494a-b374-e7a68e5ca607.jpg","thumbnailBadgeList":[],"up":true,"rest":false},{"rank":3,"titleId":828920,"titleName":"청춘 러브썸","author":{"writers":[{"id":335118,"name":"홍덕"}],"painters":[{"id":335119,"name":"NEMONE"}],"originAuthors":[]},"displayAuthor":"홍덕 / NEMONE","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/828920/thumbnail/thumbnail_IMAG21_19ce0f7d-7134-403a-bbc5-4f939cd8927f.jpg","thumbnailBadgeList":[],"up":true,"rest":false},{"rank":4,"titleId":819223,"titleName":"암호는 002!","author":{"writers":[{"id":373543,"name":"파도"}],"painters":[{"id":373543,"name":"파도"}],"originAuthors":[]},"displayAuthor":"파도","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/819223/thumbnail/thumbnail_IMAG21_1c23459c-bd74-4054-ae24-1dd4cf215dd0.jpg","thumbnailBadgeList":[],"up":true,"rest":false},{"rank":5,"rankUp":1,"titleId":817366,"titleName":"내 남편의 정부에게","author":{"writers":[{"id":343001,"name":"에리카","blogUrl":"https://blog.naver.com/erica_-"}],"painters":[{"id":371936,"name":"댄싱브레인"}],"originAuthors":[{"id":371934,"name":"라치크"}]},"displayAuthor":"에리카 / 댄싱브레인 / 라치크","thumbnailUrl":"https://image-comic.pstatic.net/webtoon/817366/thumbnail/thumbnail_IMAG21_358d6676-51bf-4a54-b4ff-b55edf907efe.jpg","thumbnailBadgeList":[],"up":true,"rest":false}]}'

In [286]:
response.headers

{'date': 'Tue, 24 Dec 2024 02:33:02 GMT', 'content-type': 'application/json', 'transfer-encoding': 'chunked', 'set-cookie': 'XSRF-TOKEN=db2ccc15-78cd-413c-98b2-06407c6fb1e4; Path=/', 'x-content-type-options': 'nosniff', 'x-xss-protection': '1; mode=block', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'x-frame-options': 'SAMEORIGIN', 'vary': 'accept-encoding', 'content-encoding': 'gzip', 'referrer-policy': 'unsafe-url', 'server': 'nfront'}

In [292]:
jsonData = response.json()
type(jsonData)

dict

In [302]:
jsonData

{'defaultSortType': 'total',
 'totalRankingTitleList': [{'rank': 1,
   'rankUp': 1,
   'titleId': 821597,
   'titleName': '괴력 난신',
   'author': {'writers': [{'id': 375577, 'name': '매드버드'}],
    'painters': [{'id': 375579, 'name': '김태형'}],
    'originAuthors': [{'id': 347598, 'name': '한중월야'}]},
   'displayAuthor': '매드버드 / 김태형 / 한중월야',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/821597/thumbnail/thumbnail_IMAG21_07118c59-2490-4cc9-b144-11c10f138b30.jpg',
   'thumbnailBadgeList': [],
   'up': True,
   'rest': False},
  {'rank': 2,
   'rankDown': 1,
   'titleId': 783053,
   'titleName': '김부장',
   'author': {'writers': [{'id': 351540, 'name': '박만사'},
     {'id': 364997, 'name': '남자의 이야기'}],
    'painters': [{'id': 300655,
      'name': '정종택',
      'blogUrl': 'https://blog.naver.com/jongjt0302'}],
    'originAuthors': []},
   'displayAuthor': '박만사, 남자의 이야기 / 정종택',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/783053/thumbnail/thumbnail_IMAG21_d7732f14-26da-4e35-8762-660cc87b53f1.jpg',
   'thumbnailBadgeList': [],
   'up': True,
   'rest': False},
  {'rank': 3,
   'titleId': 730656,
   'titleName': '사신소년',
   'author': {'writers': [{'id': 326532,
      'name': '류',
      'blogUrl': 'https://blog.naver.com/gyeonghun0617'}],
    'painters': [{'id': 326532,
      'name': '류',
      'blogUrl': 'https://blog.naver.com/gyeonghun0617'}],
    'originAuthors': []},
   'displayAuthor': '류',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/730656/thumbnail/thumbnail_IMAG21_fc6d8dbf-eed2-43d0-af45-2edb3cc4244e.jpg',
   'thumbnailBadgeList': [],
   'up': True,
   'rest': False},
  {'rank': 4,
   'titleId': 828715,
   'titleName': '절대회귀',
   'author': {'writers': [{'id': 348256, 'name': 'JP'}],
    'painters': [{'id': 325491,
      'name': '박진환',
      'blogUrl': 'https://blog.naver.com/tdstudio'}],
    'originAuthors': [{'id': 376586, 'name': '장영훈'}]},
   'displayAuthor': 'JP / 박진환 / 장영훈',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/828715/thumbnail/thumbnail_IMAG21_8957548a-2eb2-4ddf-a50e-dbc7fddc16a7.jpg',
   'thumbnailBadgeList': [],
   'up': True,
   'rest': False},
  {'rank': 5,
   'titleId': 641253,
   'titleName': '외모지상주의',
   'author': {'writers': [{'id': 283063,
      'name': '박태준',
      'blogUrl': 'https://blog.naver.com/thesooha'}],
    'painters': [{'id': 283063,
      'name': '박태준',
      'blogUrl': 'https://blog.naver.com/thesooha'}],
    'originAuthors': []},
   'displayAuthor': '박태준',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/641253/thumbnail/thumbnail_IMAG21_01672165-03c8-44b1-ba0e-ef82c9cfcd10.jpg',
   'thumbnailBadgeList': [],
   'up': False,
   'rest': False}],
 'maleRankingTitleList': [{'rank': 1,
   'titleId': 783053,
   'titleName': '김부장',
   'author': {'writers': [{'id': 351540, 'name': '박만사'},
     {'id': 364997, 'name': '남자의 이야기'}],
    'painters': [{'id': 300655,
      'name': '정종택',
      'blogUrl': 'https://blog.naver.com/jongjt0302'}],
    'originAuthors': []},
   'displayAuthor': '박만사, 남자의 이야기 / 정종택',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/783053/thumbnail/thumbnail_IMAG21_d7732f14-26da-4e35-8762-660cc87b53f1.jpg',
   'thumbnailBadgeList': [],
   'up': True,
   'rest': False},
  {'rank': 2,
   'titleId': 821597,
   'titleName': '괴력 난신',
   'author': {'writers': [{'id': 375577, 'name': '매드버드'}],
    'painters': [{'id': 375579, 'name': '김태형'}],
    'originAuthors': [{'id': 347598, 'name': '한중월야'}]},
   'displayAuthor': '매드버드 / 김태형 / 한중월야',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/821597/thumbnail/thumbnail_IMAG21_07118c59-2490-4cc9-b144-11c10f138b30.jpg',
   'thumbnailBadgeList': [],
   'up': True,
   'rest': False},
  {'rank': 3,
   'titleId': 730656,
   'titleName': '사신소년',
   'author': {'writers': [{'id': 326532,
      'name': '류',
      'blogUrl': 'https://blog.naver.com/gyeonghun0617'}],
    'painters': [{'id': 326532,
      'name': '류',
      'blogUrl': 'https://blog.naver.com/gyeonghun0617'}],
    'originAuthors': []},
   'displayAuthor': '류',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/730656/thumbnail/thumbnail_IMAG21_fc6d8dbf-eed2-43d0-af45-2edb3cc4244e.jpg',
   'thumbnailBadgeList': [],
   'up': True,
   'rest': False},
  {'rank': 4,
   'titleId': 828715,
   'titleName': '절대회귀',
   'author': {'writers': [{'id': 348256, 'name': 'JP'}],
    'painters': [{'id': 325491,
      'name': '박진환',
      'blogUrl': 'https://blog.naver.com/tdstudio'}],
    'originAuthors': [{'id': 376586, 'name': '장영훈'}]},
   'displayAuthor': 'JP / 박진환 / 장영훈',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/828715/thumbnail/thumbnail_IMAG21_8957548a-2eb2-4ddf-a50e-dbc7fddc16a7.jpg',
   'thumbnailBadgeList': [],
   'up': True,
   'rest': False},
  {'rank': 5,
   'rankUp': 1,
   'titleId': 809618,
   'titleName': '신과함께 돌아온 기사왕님',
   'author': {'writers': [{'id': 367063, 'name': '지대공마법소년'}],
    'painters': [{'id': 366485, 'name': '전천후마검사'}],
    'originAuthors': [{'id': 366484, 'name': '사람살려.'}]},
   'displayAuthor': '지대공마법소년 / 전천후마검사 / 사람살려.',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/809618/thumbnail/thumbnail_IMAG21_d3c27ef7-aa89-44d3-8be2-5b102b8aa817.jpg',
   'thumbnailBadgeList': [],
   'up': True,
   'rest': False}],
 'femaleRankingTitleList': [{'rank': 1,
   'titleId': 801711,
   'titleName': '시한부인 줄 알았어요!',
   'author': {'writers': [{'id': 359014, 'name': '혜용'}],
    'painters': [{'id': 359015,
      'name': '에시',
      'blogUrl': 'https://blog.naver.com/boria_0'}],
    'originAuthors': [{'id': 357680, 'name': '최아리'}]},
   'displayAuthor': '혜용 / 에시 / 최아리',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/801711/thumbnail/thumbnail_IMAG21_2a097d0a-8844-4fb6-93d9-fc04fb3197db.jpg',
   'thumbnailBadgeList': [],
   'up': True,
   'rest': False},
  {'rank': 2,
   'titleId': 817247,
   'titleName': '못 잡아먹어서 안달',
   'author': {'writers': [{'id': 371824, 'name': '팀 보도뵈'}],
    'painters': [{'id': 347092, 'name': '퀀퀀'}],
    'originAuthors': [{'id': 351605, 'name': '플아다'}]},
   'displayAuthor': '팀 보도뵈 / 퀀퀀 / 플아다',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/817247/thumbnail/thumbnail_IMAG21_61bd3fbe-b16f-494a-b374-e7a68e5ca607.jpg',
   'thumbnailBadgeList': [],
   'up': True,
   'rest': False},
  {'rank': 3,
   'titleId': 828920,
   'titleName': '청춘 러브썸',
   'author': {'writers': [{'id': 335118, 'name': '홍덕'}],
    'painters': [{'id': 335119, 'name': 'NEMONE'}],
    'originAuthors': []},
   'displayAuthor': '홍덕 / NEMONE',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/828920/thumbnail/thumbnail_IMAG21_19ce0f7d-7134-403a-bbc5-4f939cd8927f.jpg',
   'thumbnailBadgeList': [],
   'up': True,
   'rest': False},
  {'rank': 4,
   'titleId': 819223,
   'titleName': '암호는 002!',
   'author': {'writers': [{'id': 373543, 'name': '파도'}],
    'painters': [{'id': 373543, 'name': '파도'}],
    'originAuthors': []},
   'displayAuthor': '파도',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/819223/thumbnail/thumbnail_IMAG21_1c23459c-bd74-4054-ae24-1dd4cf215dd0.jpg',
   'thumbnailBadgeList': [],
   'up': True,
   'rest': False},
  {'rank': 5,
   'rankUp': 1,
   'titleId': 817366,
   'titleName': '내 남편의 정부에게',
   'author': {'writers': [{'id': 343001,
      'name': '에리카',
      'blogUrl': 'https://blog.naver.com/erica_-'}],
    'painters': [{'id': 371936, 'name': '댄싱브레인'}],
    'originAuthors': [{'id': 371934, 'name': '라치크'}]},
   'displayAuthor': '에리카 / 댄싱브레인 / 라치크',
   'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/817366/thumbnail/thumbnail_IMAG21_358d6676-51bf-4a54-b4ff-b55edf907efe.jpg',
   'thumbnailBadgeList': [],
   'up': True,
   'rest': False}]}

In [304]:
jsonData.get('totalRankingTitleList')

[{'rank': 1,
  'rankUp': 1,
  'titleId': 821597,
  'titleName': '괴력 난신',
  'author': {'writers': [{'id': 375577, 'name': '매드버드'}],
   'painters': [{'id': 375579, 'name': '김태형'}],
   'originAuthors': [{'id': 347598, 'name': '한중월야'}]},
  'displayAuthor': '매드버드 / 김태형 / 한중월야',
  'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/821597/thumbnail/thumbnail_IMAG21_07118c59-2490-4cc9-b144-11c10f138b30.jpg',
  'thumbnailBadgeList': [],
  'up': True,
  'rest': False},
 {'rank': 2,
  'rankDown': 1,
  'titleId': 783053,
  'titleName': '김부장',
  'author': {'writers': [{'id': 351540, 'name': '박만사'},
    {'id': 364997, 'name': '남자의 이야기'}],
   'painters': [{'id': 300655,
     'name': '정종택',
     'blogUrl': 'https://blog.naver.com/jongjt0302'}],
   'originAuthors': []},
  'displayAuthor': '박만사, 남자의 이야기 / 정종택',
  'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/783053/thumbnail/thumbnail_IMAG21_d7732f14-26da-4e35-8762-660cc87b53f1.jpg',
  'thumbnailBadgeList': [],
  'up': True,
  'rest': False},
 {'rank': 3,
  'titleId': 730656,
  'titleName': '사신소년',
  'author': {'writers': [{'id': 326532,
     'name': '류',
     'blogUrl': 'https://blog.naver.com/gyeonghun0617'}],
   'painters': [{'id': 326532,
     'name': '류',
     'blogUrl': 'https://blog.naver.com/gyeonghun0617'}],
   'originAuthors': []},
  'displayAuthor': '류',
  'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/730656/thumbnail/thumbnail_IMAG21_fc6d8dbf-eed2-43d0-af45-2edb3cc4244e.jpg',
  'thumbnailBadgeList': [],
  'up': True,
  'rest': False},
 {'rank': 4,
  'titleId': 828715,
  'titleName': '절대회귀',
  'author': {'writers': [{'id': 348256, 'name': 'JP'}],
   'painters': [{'id': 325491,
     'name': '박진환',
     'blogUrl': 'https://blog.naver.com/tdstudio'}],
   'originAuthors': [{'id': 376586, 'name': '장영훈'}]},
  'displayAuthor': 'JP / 박진환 / 장영훈',
  'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/828715/thumbnail/thumbnail_IMAG21_8957548a-2eb2-4ddf-a50e-dbc7fddc16a7.jpg',
  'thumbnailBadgeList': [],
  'up': True,
  'rest': False},
 {'rank': 5,
  'titleId': 641253,
  'titleName': '외모지상주의',
  'author': {'writers': [{'id': 283063,
     'name': '박태준',
     'blogUrl': 'https://blog.naver.com/thesooha'}],
   'painters': [{'id': 283063,
     'name': '박태준',
     'blogUrl': 'https://blog.naver.com/thesooha'}],
   'originAuthors': []},
  'displayAuthor': '박태준',
  'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/641253/thumbnail/thumbnail_IMAG21_01672165-03c8-44b1-ba0e-ef82c9cfcd10.jpg',
  'thumbnailBadgeList': [],
  'up': False,
  'rest': False}]

In [312]:
total = jsonData.get('totalRankingTitleList')
total['titleName']

TypeError: list indices must be integers or slices, not str

In [314]:
total[1]

{'rank': 2,
 'rankDown': 1,
 'titleId': 783053,
 'titleName': '김부장',
 'author': {'writers': [{'id': 351540, 'name': '박만사'},
   {'id': 364997, 'name': '남자의 이야기'}],
  'painters': [{'id': 300655,
    'name': '정종택',
    'blogUrl': 'https://blog.naver.com/jongjt0302'}],
  'originAuthors': []},
 'displayAuthor': '박만사, 남자의 이야기 / 정종택',
 'thumbnailUrl': 'https://image-comic.pstatic.net/webtoon/783053/thumbnail/thumbnail_IMAG21_d7732f14-26da-4e35-8762-660cc87b53f1.jpg',
 'thumbnailBadgeList': [],
 'up': True,
 'rest': False}

In [316]:
total[1]['titleName']

'김부장'

In [320]:
for rank in total: print(rank['rank'], ":", rank["titleName"])

1 : 괴력 난신
2 : 김부장
3 : 사신소년
4 : 절대회귀
5 : 외모지상주의

In [322]:
a = [1,2,3,4,5]
for r in a:
    print(r)

1
2
3
4
5

In [21]:
import numpy as np

#aList = [1,2,3,4,5]
aList = [1,-2,3,4.5,-5,10,-100]
type(aList)
arr = np.array(aList)
type(arr) #numpy.ndarray

np.amax(arr)
np.absolute(arr)

array([  1. ,   2. ,   3. ,   4.5,   5. ,  10. , 100. ])

In [37]:
a = np.array([[0,1,2],[3,4,5]])
b = a.transpose()
a

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
print('b\n',b)

b
 [[0 3]
 [1 4]
 [2 5]]

In [45]:
c = a.T
c

array([[0, 3],
       [1, 4],
       [2, 5]])

정규는 나쁜놈이다!
(feat.정규분포도)

In [52]:
import pandas as pd

aList = [1,2,3,4,5]
a = pd.Series([1,2,3,4,5])

a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [54]:
b = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
b

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [56]:
b['b']

2

In [58]:
b.count()

5

In [98]:
import numpy as np
import pandas as pd
'''
arr1 = np.array([['한빛','남자','20','180'],
                 ['한경','남자','21','177'],
                 ['한라','여자','20','160']])
'''
arr1 = np.array([['한빛','남자',20,180],
                 ['한경','남자','21','177'],
                 ['한라','여자','20','160']])
#'''

#list --> nbarray --> pd.DataFrame
col_names = ['이름','성별','나이','키']
df = pd.DataFrame(arr1, columns = col_names)
df

   이름  성별  나이    키
0  한빛  남자  20  180
1  한경  남자  21  177
2  한라  여자  20  160

In [100]:
df['이름']

0    한빛
1    한경
2    한라
Name: 이름, dtype: object

In [102]:
type(df['이름'])

pandas.core.series.Series

데이터 핸들링을 아래와 같은 기법을 통해 해야한다.

In [108]:
df[['이름', '성별']]

   이름  성별
0  한빛  남자
1  한경  남자
2  한라  여자

파일처리로 가볼게여(대충 6장이라는 뜻)

In [127]:
df.to_csv('./file.csv', header=True, index=False, encoding='utf-8')
df2 = pd.read_csv("C:/ws/HD_Rotem2_pycode/data_study_01/06장/chocolate_rating.csv", sep=',')

In [129]:
df2

         1  2016  0.63   3.75
0        2  2015   0.70  2.75
1        3  2015   0.70  3.00
2        4  2015   0.70  3.50
3        5  2015   0.70  3.50
4        6  2014   0.70  2.75
...    ...   ...    ...   ...
1789  1791  2011   0.70  3.75
1790  1792  2011   0.65  3.00
1791  1793  2011   0.65  3.50
1792  1794  2011   0.62  3.25
1793  1795  2010   0.65  3.00

[1794 rows x 4 columns]

In [135]:
df2.describe() #기초통계량

                 1         2016        0.63          3.75
count  1794.000000  1794.000000  1794.000000  1794.000000
mean    898.500000  2012.323300     0.717051     3.185619
std     518.027509     2.926739     0.063214     0.478010
min       2.000000  2006.000000     0.420000     1.000000
25%     450.250000  2010.000000     0.700000     2.812500
50%     898.500000  2013.000000     0.700000     3.250000
75%    1346.750000  2015.000000     0.750000     3.500000
max    1795.000000  2017.000000     1.000000     5.000000

In [137]:
list1 = list([['허준호', '남자', 30, 183],
 ['이가원', '여자', 24, 162],
 ['배규민', '남자', 23, 179],
 ['고고림', '남자', 21, 182],
 ['이새봄', '여자', 28, 160],
 ['이보람', '여자', 26, 163],
 ['이루리', '여자', 24, 157],
 ['오다현', '여자', 24, 172]])

정형화된 자료구조인 것을 확인 할 수 있다.

In [142]:
list1

[['허준호', '남자', 30, 183],
 ['이가원', '여자', 24, 162],
 ['배규민', '남자', 23, 179],
 ['고고림', '남자', 21, 182],
 ['이새봄', '여자', 28, 160],
 ['이보람', '여자', 26, 163],
 ['이루리', '여자', 24, 157],
 ['오다현', '여자', 24, 172]]

문자열로 처리하고 있다 ==> numpy의 ndarray로 처리 가능하다

In [147]:
type(list1)

list

자료형에 대해 알아야하는 것 ==> 각 자료마다 사용가능한 메소드가 다르기 때문임

In [151]:
list1[1]

['이가원', '여자', 24, 162]

여자라는 성별을 알고싶다. list1[1,1]? 안된다 python의 list객체는 이러한 접근이 허용되지 않는다 ==> list[1][1]

In [159]:
list1[1][1]

'여자'

클래스가 다르다는 것은 객체에 대한 정의가 다르다는 뜻이기에... 클래스에 대한 정의가 올바른지 확인하는 것이 디버깅의 시작이다.

기본은 입력과 출력에 대한 것에 정의가 잘 되어야 한다.

이러한 언어들에 대한 기본에 출실하는 것이 실전에 대한 준비이며, 예의이다.

list1을 numpy구조로 바꾸고 싶다면?